name: Check flight prices

on:
  workflow_dispatch:

  schedule:
    - cron: '17 9 21-29/2 9 *'
      timezone: 'Europe/Berlin'

    - cron: '17 9 1-25/2 10 *'
      timezone: 'Europe/Berlin'

jobs:
  check-flights:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.13'

      - name: Check flight prices
        env:
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
        run: python flight_search.py